name: CI  
  
on:  
  push:  
    branches:  
      - master  
  pull_request:  
    branches:  
      - master  
  
jobs:  
  build-linux-x64:  
    name: Build Linux x64  
    runs-on: ubuntu-latest  
    permissions:  
      contents: write  
    steps:  
    - uses: actions/checkout@v4  
    - name: apt update  
      run: sudo apt-get -o Acquire::Retries=3 update  
    - name: install opengl  
      run: sudo apt-get -o Acquire::Retries=3 install mesa-common-dev libgl1-mesa-dev libgl1 libglx-mesa0 libxext-dev  
    - name: install gtk  
      run: sudo apt-get -o Acquire::Retries=3 install libgtk-3-dev  
    - name: cmake  
      run: cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=/usr -DCPACK_PACKAGING_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DGIT_WXWIDGETS_SUBMODULES=ON -DwxUSE_SYS_LIBS=OFF  
    - name: build and package TreeSheets  
      run: cmake --build _build --target package -j4  
    - name: Remove epoch from .deb filename  
      run: for file in _build/treesheets_1:*.deb; do mv -v "${file}" "${file/treesheets_1:/treesheets_}"; done  
    - name: Create release  
      if: github.event_name == 'push'  
      uses: ncipollo/release-action@v1  
      with:  
        tag: ${{ github.run_id }}  
        allowUpdates: true  
        omitBody: true  
        commit: ${{ github.sha }}  
        artifacts: "_build/treesheets_*.deb"  
    - name: Upload artifacts  
      if: github.event_name == 'pull_request'  
      uses: actions/upload-artifact@v4  
      with:  
        name: linux-x64-builds  
        path: _build/treesheets_*.deb  
  
  build-linux-arm64:  
    name: Build Linux ARM64  
    runs-on: ubuntu-latest  
    permissions:  
      contents: write  
    steps:  
    - uses: actions/checkout@v4  
    - name: Set up QEMU  
      uses: docker/setup-qemu-action@v3  
      with:  
        platforms: arm64  
    - name: Set up Docker Buildx  
      uses: docker/setup-buildx-action@v3  
    - name: Build in ARM64 container  
      run: |  
        docker run --rm --platform linux/arm64 \  
          -v ${{ github.workspace }}:/workspace \  
          -w /workspace \  
          arm64v8/ubuntu:22.04 \  
          bash -c "  
            apt-get update && \  
            apt-get install -y cmake g++ git mesa-common-dev libgl1-mesa-dev libgl1 libglx-mesa0 libxext-dev libgtk-3-dev dpkg-dev file && \  
            cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=/usr -DCPACK_PACKAGING_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DGIT_WXWIDGETS_SUBMODULES=ON -DwxUSE_SYS_LIBS=OFF && \  
            cmake --build _build --target package -j4  
          "  
    - name: Remove epoch from .deb filename  
      run: for file in _build/treesheets_1:*.deb; do mv -v "${file}" "${file/treesheets_1:/treesheets_}"; done  
    - name: Create release  
      if: github.event_name == 'push'  
      uses: ncipollo/release-action@v1  
      with:  
        tag: ${{ github.run_id }}  
        allowUpdates: true  
        omitBody: true  
        commit: ${{ github.sha }}  
        artifacts: "_build/treesheets_*.deb"  
    - name: Upload artifacts  
      if: github.event_name == 'pull_request'  
      uses: actions/upload-artifact@v4  
      with:  
        name: linux-arm64-builds  
        path: _build/treesheets_*.deb  
  
  build-windows:  
    name: Build Windows x64  
    runs-on: windows-latest  
    permissions:  
      contents: write  
    steps:  
    - uses: actions/checkout@v4  
    - name: Add msbuild to PATH  
      uses: microsoft/setup-msbuild@v1.1  
    - name: cmake  
      run: cmake -S . -B _build -DCMAKE_BUILD_TYPE=Release -DGIT_WXWIDGETS_SUBMODULES=ON  
    - name: build and package  
      run: cmake --build _build --config Release --target package -j  
    - name: Create release  
      if: github.event_name == 'push'  
      uses: ncipollo/release-action@v1  
      with:  
        tag: ${{ github.run_id }}  
        allowUpdates: true  
        omitBody: true  
        commit: ${{ github.sha }}  
        artifacts: "_build/TreeSheets-*.exe, _build/TreeSheets-*.zip"  
    - name: Upload artifacts  
      if: github.event_name == 'pull_request'  
      uses: actions/upload-artifact@v4  
      with:  
        name: windows-builds  
        path: |  
          _build/TreeSheets-*.exe  
          _build/TreeSheets-*.zip